# Generated by Django 5.2.4 on 2025-11-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/', verbose_name='Видео демонстрация'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео (альтернатива)'),
        ),
    ]
